// <auto-generated />
using System;
using EventoSismicoApp.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventoSismicoApp.Migrations
{
    [DbContext(typeof(SismosDbContext))]
    [Migration("20251111015907_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("EventoSismicoApp.Entities.AlcanceSismo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AlcancesSismos");
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.CambioEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmpleadoResponsableId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventoSismicoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaHoraFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoResponsableId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("EventoSismicoId");

                    b.ToTable("CambiosDeEstado");
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.ClasificacionSismo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("KmProfundidadDesde")
                        .HasColumnType("REAL");

                    b.Property<double>("KmProfundidadHasta")
                        .HasColumnType("REAL");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClasificacionesSismos");
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.DetalleMuestraSismica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MuestraSismicaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoDatoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MuestraSismicaId");

                    b.HasIndex("TipoDatoId");

                    b.ToTable("DetallesMuestrasSismicas");
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.EstacionSismologica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoEstacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitud")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitud")
                        .HasColumnType("REAL");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EstacionesSismologicas");
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ambito")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.EventoSismico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlcanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClasificacionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsAutoDetectado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoActualId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaHoraFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHoraOcurrencia")
                        .HasColumnType("TEXT");

                    b.Property<double>("LatitudEpicentro")
                        .HasColumnType("REAL");

                    b.Property<double>("LatitudHipocentro")
                        .HasColumnType("REAL");

                    b.Property<double>("LongitudEpicentro")
                        .HasColumnType("REAL");

                    b.Property<double>("LongitudHipocentro")
                        .HasColumnType("REAL");

                    b.Property<int>("OrigenId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ValorMagnitud")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AlcanceId");

                    b.HasIndex("ClasificacionId");

                    b.HasIndex("EstadoActualId");

                    b.HasIndex("OrigenId");

                    b.ToTable("EventosSismicos");
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.MuestraSismica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaHoraMuestra")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SerieTemporalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SerieTemporalId");

                    b.ToTable("MuestrasSismicas");
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.OrigenDeGeneracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OrigenesDeGeneracion");
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.SerieTemporal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CondicionAlarma")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventoSismicoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaHoraInicioRegistroMuestras")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHoraRegistro")
                        .HasColumnType("TEXT");

                    b.Property<double>("FrecuenciaMuestreo")
                        .HasColumnType("REAL");

                    b.Property<int>("SismografoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventoSismicoId");

                    b.HasIndex("SismografoId");

                    b.ToTable("SeriesTemporales");
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.Sesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaHoraFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Sesiones");
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.Sismografo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstacionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaAdquisicion")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentificadorSismografo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EstacionId");

                    b.ToTable("Sismografos");
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.TipoDato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Denominacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUnidadMedida")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ValorUmbral")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("TiposDeDato");
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.CambioEstado", b =>
                {
                    b.HasOne("EventoSismicoApp.Entities.Empleado", "EmpleadoResponsable")
                        .WithMany()
                        .HasForeignKey("EmpleadoResponsableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventoSismicoApp.Entities.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventoSismicoApp.Entities.EventoSismico", null)
                        .WithMany("CambiosEstado")
                        .HasForeignKey("EventoSismicoId");

                    b.Navigation("EmpleadoResponsable");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.DetalleMuestraSismica", b =>
                {
                    b.HasOne("EventoSismicoApp.Entities.MuestraSismica", null)
                        .WithMany("Detalles")
                        .HasForeignKey("MuestraSismicaId");

                    b.HasOne("EventoSismicoApp.Entities.TipoDato", "TipoDato")
                        .WithMany()
                        .HasForeignKey("TipoDatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoDato");
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.EventoSismico", b =>
                {
                    b.HasOne("EventoSismicoApp.Entities.AlcanceSismo", "Alcance")
                        .WithMany()
                        .HasForeignKey("AlcanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventoSismicoApp.Entities.ClasificacionSismo", "Clasificacion")
                        .WithMany()
                        .HasForeignKey("ClasificacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventoSismicoApp.Entities.Estado", "EstadoActual")
                        .WithMany()
                        .HasForeignKey("EstadoActualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventoSismicoApp.Entities.OrigenDeGeneracion", "Origen")
                        .WithMany()
                        .HasForeignKey("OrigenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alcance");

                    b.Navigation("Clasificacion");

                    b.Navigation("EstadoActual");

                    b.Navigation("Origen");
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.MuestraSismica", b =>
                {
                    b.HasOne("EventoSismicoApp.Entities.SerieTemporal", null)
                        .WithMany("Muestras")
                        .HasForeignKey("SerieTemporalId");
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.SerieTemporal", b =>
                {
                    b.HasOne("EventoSismicoApp.Entities.EventoSismico", null)
                        .WithMany("SeriesTemporales")
                        .HasForeignKey("EventoSismicoId");

                    b.HasOne("EventoSismicoApp.Entities.Sismografo", "Sismografo")
                        .WithMany()
                        .HasForeignKey("SismografoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sismografo");
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.Sesion", b =>
                {
                    b.HasOne("EventoSismicoApp.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.Sismografo", b =>
                {
                    b.HasOne("EventoSismicoApp.Entities.EstacionSismologica", "Estacion")
                        .WithMany()
                        .HasForeignKey("EstacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estacion");
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.Usuario", b =>
                {
                    b.HasOne("EventoSismicoApp.Entities.Empleado", "Empleado")
                        .WithOne("Usuario")
                        .HasForeignKey("EventoSismicoApp.Entities.Usuario", "EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.Empleado", b =>
                {
                    b.Navigation("Usuario")
                        .IsRequired();
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.EventoSismico", b =>
                {
                    b.Navigation("CambiosEstado");

                    b.Navigation("SeriesTemporales");
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.MuestraSismica", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("EventoSismicoApp.Entities.SerieTemporal", b =>
                {
                    b.Navigation("Muestras");
                });
#pragma warning restore 612, 618
        }
    }
}
